# Generated by Django 3.2.10 on 2021-12-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datepicker',
            name='date_slug',
        ),
        migrations.AlterField(
            model_name='datepicker',
            name='date_picked',
            field=models.DateField(unique=True),
        ),
    ]
