# Generated by Django 3.2.10 on 2021-12-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_remove_datepicker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepicker',
            name='date_picked',
            field=models.DateField(),
        ),
    ]
