# Generated by Django 3.2.10 on 2021-12-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_alter_datepicker_date_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepicker',
            name='slug',
            field=models.SlugField(default=111, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datepicker',
            name='date_picked',
            field=models.DateField(unique=True),
        ),
    ]
