# Generated by Django 3.2.10 on 2021-12-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_datepicker_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datepicker',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='datepicker',
            name='slug',
        ),
    ]
