# Generated by Django 3.2.10 on 2021-12-26 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0008_auto_20211223_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_journey', models.DateField(verbose_name='Date of the Journey')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('address_start', models.CharField(blank=True, max_length=100, null=True, verbose_name='Start (full address)')),
                ('postcode_start', models.CharField(blank=True, max_length=100, null=True, verbose_name='Start Postcode')),
                ('latitude_start', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude_start', models.DecimalField(decimal_places=10, max_digits=19)),
                ('address_destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination (full address)')),
                ('postcode_destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination Postcode')),
                ('latitude_destination', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude_destination', models.DecimalField(decimal_places=10, max_digits=19)),
                ('distance', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Distance Travelled')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
