# Generated by Django 3.2.10 on 2021-12-26 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0009_journeys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journeys',
            new_name='Journey',
        ),
    ]
