# Generated by Django 3.2.10 on 2021-12-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_rename_journeys_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
