# Generated by Django 3.2.10 on 2021-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_alter_journey_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='latitude_destination',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='latitude_start',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='longitude_destination',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='longitude_start',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
