# Generated by Django 3.2.10 on 2021-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_auto_20211227_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='Distance Travelled'),
        ),
    ]
