# Generated by Django 3.2.10 on 2022-01-08 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0017_datepicker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='address_destination',
            field=models.CharField(max_length=100, verbose_name='Destination (full address)'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='address_start',
            field=models.CharField(max_length=100, verbose_name='Start (full address)'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='date_of_journey',
            field=models.DateField(blank=True, verbose_name='Date of the Journey'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, verbose_name='Distance Travelled'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='latitude_destination',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journey',
            name='latitude_start',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journey',
            name='longitude_destination',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journey',
            name='longitude_start',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journey',
            name='postcode_destination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destination Postcode'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='postcode_start',
            field=models.CharField(blank=True, max_length=100, verbose_name='Start Postcode'),
        ),
    ]
