# Generated by Django 3.2.10 on 2022-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0019_alter_journey_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='latitude_destination',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='journey',
            name='latitude_start',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='journey',
            name='longitude_destination',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='journey',
            name='longitude_start',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
