# Generated by Django 3.2.10 on 2022-01-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='town',
        ),
    ]
