# Generated by Django 3.2.10 on 2021-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_ref_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Employee Refference Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Employer Organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
