# Generated by Django 3.2.10 on 2022-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220119_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employer_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Employer's Main Office"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Employer's Latitude"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Employer's Longitude"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_ref_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Your Employee Refference Number'),
        ),
    ]
