# Generated by Django 3.2.10 on 2022-01-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220120_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='your_address',
        ),
    ]
