# Generated by Django 3.2.10 on 2021-12-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('county', models.CharField(choices=[('bedfordshire', 'Bedfordshire'), ('buckinghamshire', 'Buckinghamshire'), ('cambridgeshire', 'Cambridgeshire'), ('cheshire', 'Cheshire'), ('cleveland', 'Cleveland'), ('cornwall', 'Cornwall'), ('cumbria', 'Cumbria'), ('derbyshire', 'Derbyshire'), ('devon', 'Devon'), ('dorset', 'Dorset'), ('durham', 'Durham'), ('east sussex', 'East Sussex'), ('essex', 'Essex'), ('gloucestershire', 'Gloucestershire'), ('greater london', 'Greater London'), ('greater manchester', 'Greater Manchester'), ('hampshire', 'Hampshire'), ('hertfordshire', 'Hertfordshire'), ('kent', 'Kent'), ('lancashire', 'Lancashire'), ('leicestershire', 'Leicestershire'), ('lincolnshire', 'Lincolnshire'), ('merseyside', 'Merseyside'), ('norfolk', 'Norfolk'), ('north yorkshire', 'North Yorkshire'), ('northamptonshire', 'Northamptonshire'), ('northumberland', 'Northumberland'), ('nottinghamshire', 'Nottinghamshire'), ('oxfordshire', 'Oxfordshire'), ('shropshire', 'Shropshire'), ('somerset', 'Somerset'), ('south yorkshire', 'South Yorkshire'), ('staffordshire', 'Staffordshire'), ('suffolk', 'Suffolk'), ('surrey', 'Surrey'), ('tyne and wear', 'Tyne and Wear'), ('warwickshire', 'Warwickshire'), ('west berkshire', 'West Berkshire'), ('west midlands', 'West Midlands'), ('west sussex', 'West Sussex'), ('west yorkshire', 'West Yorkshire'), ('wiltshire', 'Wiltshire'), ('worcestershire', 'Worcestershire'), ('flintshire', 'Flintshire'), ('glamorgan', 'Glamorgan'), ('merionethshire', 'Merionethshire'), ('monmouthshire', 'Monmouthshire'), ('montgomeryshire', 'Montgomeryshire'), ('pembrokeshire', 'Pembrokeshire'), ('radnorshire', 'Radnorshire'), ('anglesey', 'Anglesey'), ('breconshire', 'Breconshire'), ('caernarvonshire', 'Caernarvonshire'), ('cardiganshire', 'Cardiganshire'), ('carmarthenshire', 'Carmarthenshire'), ('denbighshire', 'Denbighshire'), ('aberdeen city', 'Aberdeen City'), ('aberdeenshire', 'Aberdeenshire'), ('angus', 'Angus'), ('argyll and bute', 'Argyll and Bute'), ('city of edinburgh', 'City of Edinburgh'), ('clackmannanshire', 'Clackmannanshire'), ('dumfries and galloway', 'Dumfries and Galloway'), ('dundee city', 'Dundee City'), ('east ayrshire', 'East Ayrshire'), ('east dunbartonshire', 'East Dunbartonshire'), ('east lothian', 'East Lothian'), ('east renfrewshire', 'East Renfrewshire'), ('eilean siar', 'Eilean Siar'), ('falkirk', 'Falkirk'), ('fife', 'Fife'), ('glasgow city', 'Glasgow City'), ('highland', 'Highland'), ('inverclyde', 'Inverclyde'), ('midlothian', 'Midlothian'), ('moray', 'Moray'), ('north ayrshire', 'North Ayrshire'), ('north lanarkshire', 'North Lanarkshire'), ('orkney islands', 'Orkney Islands'), ('perth and kinross', 'Perth and Kinross'), ('renfrewshire', 'Renfrewshire'), ('scottish borders', 'Scottish Borders'), ('shetland islands', 'Shetland Islands'), ('south ayrshire', 'South Ayrshire'), ('south lanarkshire', 'South Lanarkshire'), ('stirling', 'Stirling'), ('west dunbartonshire', 'West Dunbartonshire'), ('west lothian', 'West Lothian'), ('antrim', 'Antrim'), ('armagh', 'Armagh'), ('down', 'Down'), ('fermanagh', 'Fermanagh'), ('derry and londonderry', 'Derry and Londonderry'), ('tyrone', 'Tyrone')], default='Northamptonshire', max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('a', 'accident'), ('b', 'road blocked'), ('f', 'flood'), ('q', 'queueing traffic'), ('r', 'roadworks'), ('s', 'slow')], default='queueing traffic', max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_messages', to=settings.AUTH_USER_MODEL)),
                ('cleared', models.ManyToManyField(blank=True, related_name='cleared', to=settings.AUTH_USER_MODEL)),
                ('thanks', models.ManyToManyField(blank=True, related_name='thanks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
