# Generated by Django 3.2.10 on 2021-12-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficmessage',
            name='category',
            field=models.CharField(choices=[('accident', 'accident'), ('blocked', 'road blocked'), ('flood', 'flood'), ('queueing', 'queueing traffic'), ('roadworks', 'roadworks'), ('slow', 'slow')], default='queueing traffic', max_length=200),
        ),
        migrations.AlterField(
            model_name='trafficmessage',
            name='county',
            field=models.CharField(choices=[('aberdeen city', 'Aberdeen City'), ('aberdeenshire', 'Aberdeenshire'), ('anglesey', 'Anglesey'), ('angus', 'Angus'), ('antrim', 'Antrim'), ('argyll and bute', 'Argyll and Bute'), ('armagh', 'Armagh'), ('breconshire', 'Breconshire'), ('bedfordshire', 'Bedfordshire'), ('buckinghamshire', 'Buckinghamshire'), ('caernarvonshire', 'Caernarvonshire'), ('cambridgeshire', 'Cambridgeshire'), ('cardiganshire', 'Cardiganshire'), ('carmarthenshire', 'Carmarthenshire'), ('cheshire', 'Cheshire'), ('city of edinburgh', 'City of Edinburgh'), ('clackmannanshire', 'Clackmannanshire'), ('cleveland', 'Cleveland'), ('cornwall', 'Cornwall'), ('cumbria', 'Cumbria'), ('denbighshire', 'Denbighshire'), ('derbyshire', 'Derbyshire'), ('derry and londonderry', 'Derry and Londonderry'), ('devon', 'Devon'), ('dorset', 'Dorset'), ('down', 'Down'), ('dumfries and galloway', 'Dumfries and Galloway'), ('dundee city', 'Dundee City'), ('durham', 'Durham'), ('east ayrshire', 'East Ayrshire'), ('east dunbartonshire', 'East Dunbartonshire'), ('east lothian', 'East Lothian'), ('east renfrewshire', 'East Renfrewshire'), ('east sussex', 'East Sussex'), ('eilean siar', 'Eilean Siar'), ('essex', 'Essex'), ('falkirk', 'Falkirk'), ('fermanagh', 'Fermanagh'), ('fife', 'Fife'), ('flintshire', 'Flintshire'), ('glamorgan', 'Glamorgan'), ('glasgow city', 'Glasgow City'), ('gloucestershire', 'Gloucestershire'), ('greater london', 'Greater London'), ('greater manchester', 'Greater Manchester'), ('hampshire', 'Hampshire'), ('hertfordshire', 'Hertfordshire'), ('highland', 'Highland'), ('inverclyde', 'Inverclyde'), ('kent', 'Kent'), ('lancashire', 'Lancashire'), ('leicestershire', 'Leicestershire'), ('lincolnshire', 'Lincolnshire'), ('merionethshire', 'Merionethshire'), ('merseyside', 'Merseyside'), ('midlothian', 'Midlothian'), ('monmouthshire', 'Monmouthshire'), ('montgomeryshire', 'Montgomeryshire'), ('moray', 'Moray'), ('norfolk', 'Norfolk'), ('north ayrshire', 'North Ayrshire'), ('north lanarkshire', 'North Lanarkshire'), ('north yorkshire', 'North Yorkshire'), ('northamptonshire', 'Northamptonshire'), ('northumberland', 'Northumberland'), ('nottinghamshire', 'Nottinghamshire'), ('orkney islands', 'Orkney Islands'), ('oxfordshire', 'Oxfordshire'), ('pembrokeshire', 'Pembrokeshire'), ('perth and kinross', 'Perth and Kinross'), ('radnorshire', 'Radnorshire'), ('renfrewshire', 'Renfrewshire'), ('scottish borders', 'Scottish Borders'), ('shetland islands', 'Shetland Islands'), ('shropshire', 'Shropshire'), ('somerset', 'Somerset'), ('south ayrshire', 'South Ayrshire'), ('south lanarkshire', 'South Lanarkshire'), ('south yorkshire', 'South Yorkshire'), ('staffordshire', 'Staffordshire'), ('stirling', 'Stirling'), ('suffolk', 'Suffolk'), ('surrey', 'Surrey'), ('tyne and wear', 'Tyne and Wear'), ('tyrone', 'Tyrone'), ('warwickshire', 'Warwickshire'), ('west berkshire', 'West Berkshire'), ('west dunbartonshire', 'West Dunbartonshire'), ('west lothian', 'West Lothian'), ('west midlands', 'West Midlands'), ('west sussex', 'West Sussex'), ('west yorkshire', 'West Yorkshire'), ('wiltshire', 'Wiltshire'), ('worcestershire', 'Worcestershire')], default='Northamptonshire', max_length=200),
        ),
    ]
